### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by blade2005** [digaev/chainify-url#1]
I love the project and was thinking about making one of my own when I found this project. I love having types and it's throwing me off not having types on objects. Would it be possible to convert this to typescript?

**Comment by digaev** [comment]
I don't think so, since the library doesn't know anything about the URLs you're going to build, it's an abstract builder, where each property is either a chain ender or a part of the URL (and both of these properties are defined by the user, there are no standard/reserved names for this). But what you can do, is define custom types, like so:
```js
/**
 * @typedef {object} ChainEnderConfig
 * @property {string | URLSearchParams} search
 */

/**
 * @callback ChainEnder
 * @param {ChainEnderConfig} config
 * @returns {string}
 */

/**
 * @typedef {{build: ChainEnder, [key: string]: MyAPI}} MyAPI
 */

/**
 * @type {MyAPI}
 */
const api = chainify('https://example.com/api/v1/', {
  build: (url) => (config = {}) => {
    if (config.search) {
      // eslint-disable-next-line no-param-reassign
      url.search = new URLSearchParams(config.search).toString();
    }

    return url.href;
  },
});

console.log(api.foo.bar.build()); // https://example.com/api/v1/foo/bar
```
A screenshot from VSCode:
![image](https://user-images.githubusercontent.com/7800933/214494890-20df85c9-bd70-49ac-ad81-686e2d638a6a.png)

**Comment by blade2005** [comment]
It doesn't need to know everything. What you've written there could be turned into the interfaces for it to a degree.

the function `chainify` accepts `baseURL` and `enders`.

`baseURL` should be a string or a `URL` object.

`enders` should be an `Record` with string or symbol keys and values of a function which accepts `config` and has an unknown return (or could set to any)(or could use type generics).

The `config` it accepts is a little hard for me to understand because yes it support `search` but I'm not sure where exactly `config` is coming from. 

Anywhere that the end user can add their own thing they could also do possibly subtypes. 

Using those type defs from your example vscode kindly converts those to types.

```javascript
/**
 * @typedef {object} ChainEnderConfig
 * @property {string | URLSearchParams} search
 */
```
becomes this:
```typescript
type ChainEnderConfig = {
    search: string | URLSearchParams;
}
```

While from your sample you specify the typedef of `api` as `MyAPI` including `build` 

```
type MyAPI = {
    [key: string]: MyAPI;
    build: ChainEnder;
}
```

which could be reduced to 

```typescript
type API = {
  [key: string]: API | ChainEnder;
}
```
if i understand your types correctly.

Typescript looks to be flexible enough to make this work but I feel like I'm not grasping all of the internals of what you're doing within `pathify` and `chainify` to submit a PR for typescript.

**Comment by digaev** [comment]
The library already has [Typings](https://github.com/digaev/chainify-url/blob/master/types/index.d.ts), I don't see any reasons to rewrite it to TS (there is no difference for the end user).

Just to make it clear. In my example above I used `build` (an ender) and `config` (as a parameter of the `build` ender), but they are not part of the library, so you may create your own enders and pass any parameters to them and define your own types according to your needs.

Here is one more example (TS this time):

```ts
import chainify from "chainify-url";

// Define types

type ChainEnderConfig = {
  search: string | URLSearchParams;
}

type ChainEnder = (config: ChainEnderConfig) => Promise<any>; // Replace `any` with the actual type

type MyAPI = {
  get: ChainEnder;
} & { [key: string]: MyAPI; }; // Had to define it that way, otherwise autocomplete in VSCode doesn't work

// Create a builder (notice that I cast it to MyAPI)

const api = chainify('https://example.com/api/v1/', {
  // `get` is an ender that we will call later, it accepts `config` as a parameter
  get: (url: URL) => async (config: Partial<ChainEnderConfig> = {}) => {
    if (config.search) {
      url.search = new URLSearchParams(config.search).toString();
    }

    // Make a request
    console.log(`GET ${url.href}`);

    // Simulate the response
    return {
      status: 200,
      data: JSON.stringify([{
        id: 1,
        name: 'Anna'
      }, {
        id: 2,
        name: 'Sarah'
      }])
    };
  },
}) as MyAPI;

// GET /api/v1/users/search?sort=asc&limit=100
api.users.search.get({
  search: new URLSearchParams({
    sort: 'asc',
    limit: '100'
  })
})
  .then((res) => {
    // Convert the response to JSON (you might want to define the `User` type)
    const users = JSON.parse(res.data) as Array<{ id: number, name: string }>;

    users.forEach((user) => {
      console.log(user.id, user.name);
    });
  })
  .catch(console.error);
```

**Comment by blade2005** [comment]
Thanks!
